---

- name: "Fetch telegraf installation package | Debian"
  action: get_url
          url={{ telegraf_agent_deb_url }}
          dest=/tmp/telegraf_{{ telegraf_agent_version }}-1_amd64.deb
          mode=0440

- name: "Install telegraf package | Debian"
  action: apt
          deb=/tmp/telegraf_{{ telegraf_agent_version }}-1_amd64.deb
          state=installed
  notify: "Restart Telegraf"
  sudo: yes
