---

- name: "Suse | Adding Telegraf group"
  group:
    name: telegraf
    state: present

- name: "Suse | Adding Telegraf user"
  user:
    name: telegraf
    group: telegraf
    state: present
  become: true

- name: "Suse | Install repo dependencies for Python 2"
  zypper:
    name:
      - python-libxml2
      - python-xml
    update_cache: True
    state: present
  register: are_telegraf_dependencies_packages_installed
  until: are_telegraf_dependencies_packages_installed is succeeded
  become: true
  when: ansible_python.version.major == 2

- name: "Suse | Install repo dependencies for Python >= 3"
  zypper:
    name:
      - python3-libxml2-python
    update_cache: True
    state: present
  register: are_telegraf_dependencies_packages_installed
  until: are_telegraf_dependencies_packages_installed is succeeded
  become: true
  when: ansible_python.version.major >= 3

- name: "Suse | Add default Open Build Service repository"
  zypper_repository:
    repo: "{{ telegraf_zypper_repos[ansible_distribution|lower] | default(telegraf_zypper_repos['default']) }}"
    name: "telegraf"
    state: present
    runrefresh: True
    auto_import_keys: True
  become: true
  when: telegraf_zypper_baseurl is not defined

- name: "Suse | Add specified package repository"
  zypper_repository:
    repo: "{{ telegraf_zypper_baseurl }}"
    name: "telegraf"
    state: present
    runrefresh: True
    auto_import_keys: True
  become: true
  when: telegraf_zypper_baseurl is defined

- name: "Suse | Install Telegraf"
  zypper:
    name: "{{ telegraf_agent_package }}"
    state: "{{ telegraf_agent_package_state }}"
  register: is_telegraf_package_installed
  until: is_telegraf_package_installed is succeeded
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Suse | Create directories for telegraf"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    mode: 0755
    state: directory
  with_items:
    - path: /etc/telegraf/telegraf.d/
      owner: root
    - path: /var/log/telegraf
      owner: telegraf
